services:
  db:
    image: postgres:16
    container_name: ticket-postgres
    restart: always
    environment:
      POSTGRES_DB: Bus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vatsa
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ticket-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Bus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: vatsa

  frontend:
    build:
      context: ../FrontEnd/bus-ticket-admin # ðŸ‘ˆ point to real React app folder
      dockerfile: Dockerfile # ðŸ‘ˆ Dockerfile is in this folder
    container_name: ticket-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80" # app at http://localhost:3000

volumes:
  db-data:
