version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ticket-postgres
    restart: always
    environment:
      POSTGRES_DB: Bus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vatsa
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ticket-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Bus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: vatsa

volumes:
  db-data:
